### ISSUE TITLE
LICENSE or permission to reuse code?

### ISSUE THREAD

**Issue by sparr** [jaredkrinke/pico-8-fbg#1]
Would you be willing to add a LICENSE file to your repo, or to specifically here give me permission to modify and redistribute some of your code in my pico8 library repo https://github.com/sparr/pico8lib ?

**Comment by jaredkrinke** [comment]
Good suggestion. I licensed the code under the MIT license, but let me know if you were looking for something else. Out of curiosity, which code were you looking at pulling out?

Side note: I haven't really been updating it, but I previously put some of my reusable code in this repository:
https://github.com/jaredkrinke/pico-8-util/tree/master

**Comment by sparr** [comment]
Thanks for adding a LICENSE. 

My library primarily uses the Unlicense (https://github.com/sparr/pico8lib/blob/master/LICENSE), so if you give me permission to reuse under that license that would be ideal. MIT license is also great, there's plenty of pico8 code out there using MIT, GPL, and CC. I can simply mark your code as differently licensed, as I already have with the vector library there.

I didn't look into your code too much before asking, because I want to remain able to honestly reimplement the functionality in question if you said no, but the first and biggest thing that jumped ot at me is your `uint32` class.

**Comment by jaredkrinke** [comment]
Sure, you have my permission to use the code from those two repositories (I'm the sole author) under the Unlicense license (instead of MIT) if you prefer.

**Comment by sparr** [comment]
Thanks!
